#!/bin/bash

if [ -d bin ]
then
    rm -rf bin
fi

mkdir bin

javac src/*/*.java -classpath /home/hduser/jarHadoop/commons-cli-1.2.jar:/home/hduser/jarHadoop/hadoop-common-2.6.0.jar:/home/hduser/jarHadoop/hadoop-mapreduce-client-core-2.6.0.jar -d bin/

jar -cvf ./bin/tp1.jar -C ./bin/ .
